config/routes.rb
Rails.application.routes.draw do
  resources :users, except: [:new]
  resources :articles
  resources :categories, except: [:destroy]

  get 'home',  to: 'pages#home'
  get 'about', to: 'pages#about'

  get 'signup',     to: 'users#new'
  get 'login',      to: 'sessions#new'
  post 'login',     to: 'sessions#create'
  delete 'logout',  to: 'sessions#destroy'

  root 'pages#home'
end

app/models/article.rb
# App Article
class Article < ActiveRecord::Base
  belongs_to :user

  has_many :article_categories
  has_many :categories, through: :article_categories

  validates :title, length: { in: 3..50 }
  validates :description, length: { in: 10..500 }
  validates :user_id, presence: true
end

app/models/article_category.rb
# Many to many connection between articles and their categories.
class ArticleCategory < ActiveRecord::Base
  belongs_to :article
  belongs_to :category
end

app/models/category.rb
# Article categories, each article can have many categories
class Category < ActiveRecord::Base
  has_many :article_categories
  has_many :articles, through: :article_categories

  validates :name,
            presence: true,
            uniqueness: { case_sensitive: false },
            length: { in: 3..25 }
end

app/models/user.rb
# App User
class User < ActiveRecord::Base
  before_save { self.email = email.downcase }

  has_many :articles, dependent: :destroy

  has_secure_password

  validates :username,
            presence: true,
            length: { in: 4..25 },
            uniqueness: { case_sensitive: false }

  # This Regex is pragmatic, not exhaustive, and importantly, case-INsensitive.
  VALID_EMAIL = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i

  validates :email,
            presence: true,
            length: { maximum: 255 },
            uniqueness: { case_sensitive: false },
            format: { with: VALID_EMAIL }
end

app/controllers/application_controller.rb
# Base application controller
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.

  protect_from_forgery with: :exception

  helper_method :current_user, :current_user?, :logged_in?

  def current_user
    id = session[:user_id]
    @current_user ||= User.find(id) if id
  end

  def current_user?(user)
    current_user == user
  end

  def logged_in?
    !current_user.nil?
  end

  def require_user
    return if logged_in?

    flash[:danger] = 'You must be logged in to perform that action.'
    redirect_to root_path
  end
end

app/controllers/articles_controller.rb
# Controller for Article actions
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:show, :index]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def index
    @articles = Article.paginate page: params[:page], per_page: 10
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new article_params
    @article.user = current_user

    if @article.save
      flash[:success] = 'Your article was saved successully.'
      redirect_to article_path(@article)
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @article.update article_params
      flash[:success] = 'Your article was updated successfully.'
      redirect_to article_path(@article)
    else
      render :edit
    end
  end

  def destroy
    if @article.destroy
      flash[:danger] = 'Your article was removed successfully.'
    else
      flash[:warning] = 'Your article could not be removed.'
    end

    redirect_to articles_path
  end

  private

  def article_params
    params.require(:article).permit(:title, :description, category_ids: [])
  end

  def set_article
    @article = Article.find params[:id]
  end

  def require_same_user
    return if current_user?(@article.user) || current_user.admin?

    flash[:danger] = 'You can only edit or delete your own articles.'
    redirect_to articles_path
  end
end

app/controllers/categories_controller.rb
# Controller for article categories
class CategoriesController < ApplicationController
  before_action :set_category, only: [:edit, :update, :show]
  before_action :require_admin, except: [:index, :show]

  def index
    @categories = Category.paginate page: params[:page], per_page: 10
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new category_params

    if @category.save
      flash[:success] = 'The new category was created successfully.'
      redirect_to categories_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @category.update category_params
      flash[:success] = 'The category name was updated successfully.'
      redirect_to @category
    else
      render :edit
    end
  end

  def show
    @articles = @category.articles.paginate page: params[:page], per_page: 10
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end

  def set_category
    @category = Category.find params[:id]
  end

  def require_admin
    return if logged_in? && current_user.admin?

    flash[:danger] = 'Only admins can perform that action.'
    redirect_to categories_path
  end
end

app/controllers/pages_controller.rb
# Controller for static pages
class PagesController < ApplicationController
  def home
    redirect_to(articles_path) if logged_in?
  end

  def about
  end
end

app/controllers/sessions_controller.rb
# Controller for user login sessions
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: session_email.downcase)

    if user && user.authenticate(session_password)
      login_user user
    else
      flash.now[:danger] = 'Your email address or password were not recognised.'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'You have logged out successfully.'
    redirect_to root_path
  end

  private

  def session_params
    params[:session]
  end

  def session_password
    session_params[:password]
  end

  def session_email
    session_params[:email]
  end

  def login_user(user)
    session[:user_id] = user.id
    flash[:success] = 'You have logged in successfully.'
    redirect_to user
  end
end

app/controllers/users_controller.rb
# Users controller
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  before_action :require_admin, only: [:destroy]

  def index
    @users = User.paginate page: params[:page], per_page: 10
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params

    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Welcome to the Alpha Blog, #{@user.username}."
      redirect_to @user
    else
      render :new
    end
  end

  def show
    @articles = @user.articles.paginate page: params[:page], per_page: 10
  end

  def edit
  end

  def update
    if @user.update user_params
      flash[:success] = 'Your account was updated successfully.'
      redirect_to articles_path
    else
      render :edit
    end
  end

  def destroy
    flash[:danger] = "#{@user.username} and their articles have been removed."
    @user.destroy
    redirect_to users_path
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def set_user
    @user = User.find params[:id]
  end

  def require_same_user
    return if logged_in? && (current_user?(@user) || current_user.admin?)

    flash[:danger] = 'You can only edit your own account.'
    redirect_to users_path
  end

  def require_admin
    return if logged_in? && current_user.admin?

    flash[:danger] = 'Only admin users can perform that action.'
  end
end

app/helpers/application_helper.rb
# Common functions accessible in all views
module ApplicationHelper
  # :reek:FeatureEnvy
  def gravatar_for(user, options = { size: 80 })
    g_id = Digest::MD5.hexdigest user.email
    g_url = "https://secure.gravatar.com/avatar/#{g_id}?s=#{options[:size]}"

    image_tag(g_url, alt: user.username, class: 'img-circle gravatar')
  end
end

app/views/articles/_article.html.erb
<div class="row">
  <div class="col-xs-8 col-xs-offset-2">
    <div class="well well-lg">
      <div class="article-title">
        <%= link_to article.title, article %>
      </div>
      <div class="article-body">
        <%= truncate article.description, length: 100 %>
        <div class="article-metadata">
          <small>
            Created by <%= article.user.username %>,
            <% if article.created_at != article.updated_at %>
              <%= time_ago_in_words(article.created_at) %> ago,
              last updated <%= time_ago_in_words(article.updated_at) %> ago
            <% else %>
              <%= time_ago_in_words(article.created_at) %> ago
            <% end %>
          </small>
        </div>
      </div>

      <% if article.categories.any? %>
        <p>Categories: <%= render article.categories %></p>
      <% end %>

      <% if logged_in? && (current_user?(article.user) || current_user.admin?) %>
        <div class="article-actions">
          <%= link_to 'Edit this article', edit_article_path(article), class: 'btn btn-xs btn-primary' %>
          <%= link_to 'Delete this article', article, method: :delete,
                      data: { confirm: 'Are you sure that you want to delete this article?' },
                      class: 'btn btn-xs btn-danger' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/articles/_form.html.erb
<%= form_for @article, html: { class: 'form-horizontal', role: 'form' } do |f| %>
  <div class="form-group">
    <%= f.label :title, class: 'col-sm-2 control-label' %>
    <div class="col-sm-8">
      <%= f.text_field :title, class: 'form-control', placeholder: 'Title of Article', autofocus: true %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :description, class: 'col-sm-2 control-label' %>
    <div class="col-sm-8">
      <%= f.text_area :description, class: 'form-control', placeholder: 'Body of Article', rows: 8 %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-2 text-right">
      <strong>Categories</strong>
    </div>
    <div class="col-sm-8">
      <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
        <%= cb.label(class: 'checkbox-inline input_checkbox') {
            cb.check_box(class: 'checkbox') + cb.text } %>
      <% end %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: 'btn btn-primary btn-lg' %>
    </div>
  </div>
<% end %>

<div class="row">
  <div class="col-xs-6 col-xs-offset-4">
    [ <%= link_to 'Cancel and Return to Articles', articles_path %> ]
  </div>
</div>

app/views/articles/edit.html.erb
<div class="page-header">
  <h1>Edit Article <%= @article.id %></h1>
</div>

<%= render 'shared/errors', object: @article %>
<%= render 'form' %>

app/views/articles/index.html.erb
<div class="page-header">
  <h1>Current Articles</h1>
</div>

<div class="text-center">
  <%= will_paginate %>
</div>

<%= render @articles %>

<div class="text-center">
  <%= will_paginate %>
</div>

app/views/articles/new.html.erb
<div class="page-header">
  <h1>Create an Article</h1>
</div>

<%= render 'shared/errors', object: @article %>
<%= render 'form' %>

app/views/articles/show.html.erb
<div class="page-header">
  <h1><%= @article.title %></h1>
</div>

<div class="well col-xs-8 col-xs-offset-2">
  <ul class="listing">
    <div class="row">
      <div class="col-md-4 col-md-offset-4 text-center">
        <li>Created by: <%= link_to @article.user.username, @article.user %></li>
        <li><%= link_to gravatar_for(@article.user), @article.user %></li>
      </div>
    </div>
  </ul>

  <h4 class="text-center description"><strong>Description:</strong></h4>
  <hr>
  <%= simple_format @article.description %></p>

  <% if @article.categories.any? %>
    <p>Categories: <%= render @article.categories %></p>
  <% end %>

  <div class="article-actions">
    <% if logged_in? && (current_user?(@article.user) || current_user.admin?) %>
      <%= link_to 'Edit this Article', edit_article_path(@article), class: 'btn btn-xs btn-primary' %>
      <%= link_to 'Delete this Article', article_path(@article), method: :delete,
                  data: { confirm: 'Are you sure that you want to delete this article?' },
                  class: 'btn btn-xs btn-danger' %>
    <% end %>
    <%= link_to 'View all Articles', articles_path, class: 'btn btn-xs btn-success' %>
  </div>
</div>

app/views/categories/_category.html.erb
<span class="badge"><%= link_to category.name, category %> </span>

app/views/categories/_form.html.erb
<%= form_for @category, html: { class: 'form-horizontal', role: 'form' } do |f| %>
  <div class="form-group">
    <%= f.label :name, class: 'col-sm-2 control-label' %>
    <div class="col-sm-4">
      <%= f.text_field :name, class: 'form-control', placeholder: 'Enter category name', autofocus: true %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: 'btn btn-primary btn-lg' %>
    </div>
  </div>
<% end %>

<div class="row">
  <div class="col-xs-6 col-xs-offset-4">
    [ <%= link_to 'Cancel and Return to Articles', articles_path %> ]
  </div>
</div>

app/views/categories/edit.html.erb
<div class="page-header">
  <h1>Edit category name</h1>
</div>

<%= render 'shared/errors', object: @category %>

<%= render 'form' %>

app/views/categories/index.html.erb
<div class="page-header">
  <h1>Current categories</h1>
</div>

<%= will_paginate class: 'text-center' %>

<% @categories.each do |category| %>
  <ul class="listing">
    <div class="row">
      <div class="well well-sm col-md-4 col-md-offset-4 text-center">
        <li class="article-title">
          <%= link_to category.name, category %>
        </li>
        <li>
          <small><%= pluralize category.articles.count, 'articles' %></small>
        </li>
      </div>
    </div>
  </ul>
<% end %>

<%= will_paginate class: 'text-center' %>

app/views/categories/new.html.erb
<div class="page-header">
  <h1>Create new category</h1>
</div>

<%= render 'shared/errors', object: @category %>

<%= form_for @category, html: { class: 'form-horizontal', role: 'form' } do |f| %>
  <div class="form-group">
    <%= f.label :name, class: 'col-sm-2 control-label' %>
    <div class="col-sm-4">
      <%= f.text_field :name, class: 'form-control', placeholder: 'Enter category name', autofocus: true %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: 'btn btn-primary btn-lg' %>
    </div>
  </div>
<% end %>

<div class="row">
  <div class="col-xs-6 col-xs-offset-4">
    [ <%= link_to 'Cancel and Return to Articles', articles_path %> ]
  </div>
</div>

app/views/categories/show.html.erb
<div class="page-header">
  <% if logged_in? && current_user.admin? %>
    <div class="row">
      <div class="col-md-4">
        <h1>Category: <%= @category.name %></h1>
      </div>
      <div class="col-md-2 col-md-offset-3">
        <%= link_to 'Edit category name',
                    edit_category_path(@category),
                    class: 'btn btn-primary btn-xs move-down' %>
      </div>
    </div>
  <% else %>
    <h1>Category: <%= @category.name %></h1>
  <% end %>
</div>

<div class="text-center">
  <%= will_paginate @articles %>
</div>

<% if @articles.any? %>
  <%= render @articles %>
<% else %>
  <h4 class="text-center">No articles</h4>
<% end %>

<div class="text-center">
  <%= will_paginate @articles %>
</div>

app/views/layouts/_footer.html.erb
<div class="container">
  <footer class="footer">
    <small>
      Copyright &copy;
      <a href="https://www.udemy.com/the-complete-ruby-on-rails-developer-course">
        The Complete Ruby on Rails Developer
      </a>
      by <a href="http://www.mashrurhossain.com">Mashrur Hossain</a>
      followed by <a href="http://www.reallybigshoe.co.uk">Julian Nicholls</a>
    </small>
    <nav>
      <ul>
        <li><%= link_to 'About', about_path %></li>
      </ul>
    </nav>
  </footer>
</div>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
    <% flash.each do |name, msg| %>
      <div class="alert alert-<%= name %> alert-dismissible" role="alert">
        <a href="#" class="close" data-dismiss="alert" aria-label="Close">&#215;</a>
        <%= msg %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Alpha Blog', root_path, class: 'navbar-brand', id: 'logo' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Articles', articles_path %></li>
        <li><%= link_to 'Users', users_path %></li>
        <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Actions <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to 'Create new article', new_article_path %></li>
            </ul>
          </li>
        <% end %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Categories <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to 'All Categories', categories_path %></li>
            <% if logged_in? && current_user.admin? %>
              <li><%= link_to 'Create new category', new_category_path %></li>
            <% end %>
            <li role="separator" class="divider"></li>
            <% Category.all.each do |category| %>
              <li><%= link_to category.name, category %></li>
            <% end %>
          </ul>
        </li>
      </ul>
<!--      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>                                                               -->
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li><%= link_to 'Log out', logout_path, method: :delete %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Profile <%= '(Admin)' if current_user.admin? %> <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to 'Edit your account', edit_user_path(current_user) %></li>
              <li><%= link_to 'View your page', current_user %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to 'Log in', login_path %></li>
          <li><%= link_to 'Sign up', signup_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Alpha Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/navigation' %>
  <%= render 'layouts/messages' %>

  <div class="container">
    <%= yield %>
  </div>

  <%= render 'layouts/footer' %>
  <%= debug(params) if Rails.env.development? %>
</body>
</html>

app/views/pages/about.html.erb
<div class="page-header">
  <h1>About the Alpha Blog</h1>
</div>

<p>I don't know what to say about it yet.</p>

<p>More waffle here.</p>

app/views/pages/home.html.erb
<div class="jumbotron text-center">
  <h1>ALPHA BLOG</h1>
  <%= link_to 'Sign up Now', signup_path, class: 'btn btn-lg btn-xlarge btn-danger' %>
</div>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="panel panel-danger">
        <div class="panel-heading">
          <h2 class="panel-title">
            <%= pluralize object.errors.count, 'error' %>
            prevented the article from saving:
          </h2>
        </div>
        <div class="panel-body">
          <ol>
            <% object.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ol>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= form_for @user, html: { class: 'form-horizontal', role: 'form' } do |f| %>
  <div class="form-group">
    <%= f.label :username, class: 'col-sm-2 control-label' %>
    <div class="col-sm-8">
      <%= f.text_field :username, class: 'form-control', placeholder: 'Enter user name', autofocus: true %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :email, class: 'col-sm-2 control-label' %>
    <div class="col-sm-8">
      <%= f.email_field :email, class: 'form-control', placeholder: 'Enter Email Address' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :password, class: 'col-sm-2 control-label' %>
    <div class="col-sm-8">
      <%= f.password_field :password, class: 'form-control', placeholder: 'Enter Password' %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit(@user.new_record? ? 'Sign up' : 'Update your Account', class: 'btn btn-primary btn-lg') %>
    </div>
  </div>
<% end %>

<div class="row">
  <div class="col-xs-6 col-xs-offset-4">
    [ <%= link_to 'Cancel and Return to Articles', articles_path %> ]
  </div>
</div>

app/views/users/edit.html.erb
<div class="page-header">
  <h1>Edit your Account</h1>
</div>

<%= render 'shared/errors', object: @user %>
<%= render 'form' %>

app/views/users/index.html.erb
<div class="page-header">
  <h1>Current Alpha Bloggers</h1>
</div>
<div class="text-center">
  <%= will_paginate %>
</div>

<% @users.each do |user| %>
  <ul class="listing">
    <div class="row">
      <div class="well well-sm col-md-4 col-md-offset-4 text-center">
        <li><%= link_to gravatar_for(user), user %></li>
        <li class="article-title">
          <%= link_to user.username, user %>
        </li>
        <li>
          <small>
            <%= pluralize(user.articles.count, 'article') if user.articles %>
          </small>
        </li>
        <% if logged_in? && current_user.admin? %>
          <li>
            <%= link_to 'Delete this user', user, method: :delete,
                data: { confirm: 'Are you sure you want to delete this user and all of their articles?' },
                class: 'btn btn-danger btn-xs' %>
          </li>
        <% end %>
      </div>
    </div>
  </ul>
<% end %>

<div class="text-center">
  <%= will_paginate %>
</div>

app/views/users/new.html.erb
<div class="page-header">
  <h1>Sign up for the Alpha Blog</h1>
</div>

<%= render 'shared/errors', object: @user %>
<%= render 'form' %>

app/views/users/show.html.erb
<div class="page-header">
  <h1>Welcome to <%= @user.username %>'s page</h1>
</div>

<div class="row">
  <div class="col-md-4 col-md-offset-4 text-center">
    <%= gravatar_for @user, size: 150 %>
  </div>
</div>
<h3 class="text-center"><%= @user.username %>'s articles</h3>

<div class="text-center">
  <%= will_paginate @articles %>
</div>

<%= render @articles %>

<div class="text-center">
  <%= will_paginate @articles %>
</div>